
services:

  frontend_v14:
    networks:
      - DEX
    container_name: dex_frontend_v14
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_API=http://backend:8000

  nginx:
    networks:
      - DEX
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend_v14
  
  contract:
    networks:
      - DEX
    container_name: dex_contract
    build: 
      context: ./contract
      dockerfile: Dockerfile
    environment:
    - PORT=8545
    ports:
      - 8545:8545


  backend:
    networks:
      - DEX
    container_name: dex_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
    - PORT=8000
    - MONGODBURI=mongodb://mongo:27017/dex
    - NETWORK_URL=http://contract:8545
    ports:
      - 8000:8000
    depends_on:
      - mongo
      

    
  mongo:
    networks:
      - DEX
    image: mongo:5.0
    container_name: dex_mongo_db
    restart: always
    ports:
      - 27019:27017
    volumes:
      - mongodb:/data/db
  

networks:
  DEX:
    driver: bridge

volumes:
  mongodb: