services:
  frontend:
    networks:
      - DEX
    container_name: dex_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=${FRONTEND_PORT}
      - NETWORK_URL=${NETWORK_URL}
      - NEXT_PUBLIC_BACKEND_API=${BACKEND_URL}
      - NEXT_PUBLIC_PAYPAL_CLIENT_ID=${CLIENT_ID}
      - NEXT_PUBLIC_ADDRESS_LIMIT=${ADDRESS_ORDER_LIMIT}
      - NEXT_PUBLIC_ADDRESS_MARKET_NFT=${ADDRESS_MARKET_NFT}
    

  nginx:
    networks:
      - DEX
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
  

  contract:
    networks:
      - DEX
    container_name: dex_contract
    build: 
      context: ./contract
      dockerfile: Dockerfile
    environment:
      - PORT=${CONTRACT_PORT}
    ports:
      - 8545:8545

  backend:
    networks:
      - DEX
    container_name: dex_backend
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=${BACKEND_PORT}
      - MONGODBURI=${MONGODBURI}
      - NETWORK_URL=${NETWORK_URL}
      - SOCKET_NETWORK_URL=${NETWORK_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - PRIVATE_KEY_ADDRESS=${PRIVATE_KEY_ADDRESS}
      - CLIENT_ID=${CLIENT_ID}
      - SECRET_KEY=${SECRET_KEY}
      - ADDRESS_FACTORY_TOKEN=${ADDRESS_FACTORY_TOKEN}
      - ADDRESS_FACTORY_LIQUIDITYPOOL=${ADDRESS_FACTORY_LIQUIDITYPOOL}
      - ADDRESS_MARKET_NFT=${ADDRESS_MARKET_NFT}
      - ADDRESS_ORDER_LIMIT=${ADDRESS_ORDER_LIMIT}
      - IPFSLINK=${IPFSLINK}
      - ALCHEMY_SEPOLIA_URL=${ALCHEMY_SEPOLIA_URL}
      - PAYEE_EMAIL=${PAYEE_EMAIL}
    # ports:
    #   - 8000:8000
    depends_on:
      - mongo-primary
      - mongo-secondary1
      - mongo-secondary2
      

  mongo-primary:
    networks:
      - DEX
    image: mongo:5.0
    container_name: dex_mongo_primary
    restart: always
    ports:
      - 27019:27017
    environment:
      - MONGO_INITIATE_REPLICASET=rs0
    command: mongod --replSet "rs0" --bind_ip_all
    volumes:
      - mongodb-primary:/data/db
  
  mongo-secondary1:
    networks:
      - DEX
    image: mongo:5.0
    container_name: dex_mongo_secondary1
    restart: always
    ports:
      - 27020:27017
    environment:
      - MONGO_INITIATE_REPLICASET=rs0
    command: mongod --replSet "rs0" --bind_ip_all
    volumes:
      - mongodb-secondary1:/data/db

  mongo-secondary2:
    networks:
      - DEX
    image: mongo:5.0
    container_name: dex_mongo_secondary2
    restart: always
    ports:
      - 27021:27017
    environment:
      - MONGO_INITIATE_REPLICASET=rs0
    command: mongod --replSet "rs0" --bind_ip_all
    volumes:
      - mongodb-secondary2:/data/db
  
  rs-init:
    networks:
      - DEX
    image: mongo:5.0
    container_name: dex_rs_init
    restart: 'no'
    depends_on:
      - mongo-primary
      - mongo-secondary1
      - mongo-secondary2
    entrypoint: >
      bash -c "
      echo 'Waiting for MongoDB nodes to be ready...' &&
      sleep 10 &&
      mongo --host mongo-primary:27017 --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [
            { _id: 0, host: \"mongo-primary:27017\" },
            { _id: 1, host: \"mongo-secondary1:27017\" },
            { _id: 2, host: \"mongo-secondary2:27017\" }
          ]
        });
      ' &&
      echo 'Replica Set initialized successfully.'
      "


networks:
  DEX:
    driver: bridge

volumes:
  mongodb-primary:
  mongodb-secondary1:
  mongodb-secondary2:

