
services:

  frontend:
    networks:
      - DEX
    container_name: dex_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - api=http://backend:8000/api/

  nginx:
    networks:
      - DEX
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
  
  backend:
    networks:
      - DEX
    container_name: dex_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
    - PORT=8000
    - MONGODBURI=mongodb://mongo:27017/netflix
    ports:
      - 8000:8000
    depends_on:
      - mongo

    
  mongo:
    networks:
      - DEX
    image: mongo:5.0
    container_name: dex_mongo_db
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
  

networks:
  DEX:
    driver: bridge

volumes:
  mongodb: